(function(){
"use strict";
const P={};
const SYSTEMS={
"Naruto":{headline:"Shinobi Record",rankLabel:"Shinobi Rank",ranks:["Academy Graduate","Genin","Chūnin","Tokubetsu Jōnin","Jōnin","Elite Jōnin","Kage-class"],rankMetric:"missions",rankRequirements:[0,2,7,15,28,45,70],resource:"Chakra",tracks:{ninjutsu:"Ninjutsu",taijutsu:"Taijutsu",genjutsu:"Genjutsu",chakra:"Chakra Control",will:"Willpower"},worldRules:"Rank records trust and accomplishments, not raw power. Techniques, chakra control, lineage, Dōjutsu and Jinchūriki development advance separately."},
"One Piece":{headline:"Pirate Record",rankLabel:"World Reputation",ranks:["Unknown","Local Name","Rising Rookie","Notorious","Supernova-class","New World Threat","Emperor-class Presence"],rankMetric:"renown",rankRequirements:[0,10,30,70,140,260,450],resource:"Stamina",tracks:{combat:"Fighting Style",observation:"Observation Haki",armament:"Armament Haki",conqueror:"Conqueror's Haki",fruit:"Devil Fruit Mastery",crew:"Crew Influence"},worldRules:"Bounty and reputation are consequences of witnessed deeds, not levels. Haki, fighting style, Devil Fruit mastery and crew leadership remain independent."},
"Hunter x Hunter":{headline:"Hunter Development",rankLabel:"Hunter Standing",ranks:["Applicant","Field-Capable","Licensed Hunter","Specialist","Veteran Hunter","Elite Hunter","Legend-class"],rankMetric:"missions",rankRequirements:[0,2,6,14,26,42,65],resource:"Aura",tracks:{ten:"Ten",zetsu:"Zetsu",ren:"Ren",hatsu:"Hatsu Mastery",field:"Fieldcraft",body:"Physical Conditioning"},worldRules:"Nen fundamentals and Hatsu grow through practice, experience and restrictions. Hunter status is professional recognition, not a power tier."},
"Bleach":{headline:"Soul Reaper Record",rankLabel:"Division Standing",ranks:["Academy/Unseated","Unseated Officer","Seated Officer","Lieutenant-class","Captain-class","Senior Captain-class","Transcendent Presence"],rankMetric:"missions",rankRequirements:[0,3,8,18,34,55,85],resource:"Reiryoku",tracks:{zanjutsu:"Zanjutsu",hakuda:"Hakuda",hoho:"Hohō",kido:"Kidō",reiatsu:"Reiatsu Control",release:"Zanpakutō Bond"},worldRules:"Division standing and spiritual power are separate. Zanpakutō releases depend on relationship, mastery and experience rather than generic experience points."},
"Jujutsu Kaisen":{headline:"Jujutsu Record",rankLabel:"Official Grade",ranks:["Unassessed","Grade 4","Grade 3","Grade 2","Semi-Grade 1","Grade 1","Special Grade Candidate"],rankMetric:"missions",rankRequirements:[0,2,6,15,35,70,120],resource:"Cursed Energy",tracks:{ce:"Cursed Energy Control",technique:"Technique Mastery",combat:"Combat Skill",barrier:"Barrier Arts",society:"Jujutsu Standing"},worldRules:"Official grade depends on witnessed reliability and mission results. Technique mastery, Domain, RCT, barriers and binding vows are separate earned tracks."},
"Overgeared":{headline:"Satisfy Status",rankLabel:"Level",literalLevels:true,resource:"Mana",tracks:{class:"Class Mastery",combat:"Combat Mastery",craft:"Production Mastery",reputation:"NPC Affinity & Reputation",guild:"Guild Contribution"},worldRules:"Levels matter, but class identity, production, titles, relationships, equipment and guild contribution remain separate progression routes."},
"Solo Max-Level Newbie":{headline:"System Status",rankLabel:"Level",literalLevels:true,resource:"Mana",tracks:{combat:"Combat",skills:"Skill Mastery",copy:"Copy Capacity",system:"System Exploitation",tower:"Tower Progress"},worldRules:"Levels and stats are literal. Copied abilities, hidden conditions, achievements, titles and floor progression remain persistent system records."},
"Reincarnated as a Slime":{headline:"Evolution Record",rankLabel:"Species Stage",ranks:["Newly Manifested","Named Monster","Evolved Monster","High Majin","Demon Lord Seed","Awakened Demon Lord","Ultimate Existence"],rankMetric:"milestones",rankRequirements:[0,4,12,28,50,80,120],resource:"Magicules",tracks:{magicules:"Magicule Capacity",skills:"Skill Mastery",control:"Magicule Control",nation:"Nation & Leadership",resistance:"Resistances"},worldRules:"Species evolution, naming, skill synthesis and Demon Lord awakening require their actual triggers. Raw mastery alone does not grant an evolution."},
"Custom World":{headline:"Worldwalker Record",rankLabel:"Standing",ranks:["Unknown","Local Figure","Proven Adventurer","Regional Power","Major Figure","World Power","Legend"],rankMetric:"renown",rankRequirements:[0,8,24,60,120,220,380],resource:"Energy",tracks:{power:"Power Mastery",combat:"Combat",insight:"Insight",craft:"Craft",leadership:"Leadership"},worldRules:"Recognition and personal power stay separate. Abilities grow through use and their established costs, limits and prerequisites."}
};
function clone(v){return JSON.parse(JSON.stringify(v));}
P.systems=SYSTEMS;
P.init=function(state){const s=SYSTEMS[state.world]||SYSTEMS["Custom World"];state.progression=state.progression||{};const p=state.progression;p.headline=s.headline;p.rankLabel=s.rankLabel;p.literalLevels=!!s.literalLevels;p.metrics=p.metrics||{missions:0,renown:0,exorcisms:0,milestones:0};if(p.literalLevels){p.level=Number(p.level||state.level||1);p.xp=Number(p.xp||0);p.xpNext=Number(p.xpNext||140);p.statPoints=Number(p.statPoints||0);p.rank=String(p.level);}else{p.rankIndex=Number(p.rankIndex||0);p.rank=s.ranks[p.rankIndex]||s.ranks[0];}
p.tracks=p.tracks||{};for(const [id,label] of Object.entries(s.tracks)){p.tracks[id]=p.tracks[id]||{id,label,value:1,mastery:0,history:[]};}if(state.world==="One Piece"&&p.tracks.conqueror&&!state.special?.conquerorAwakened)p.tracks.conqueror.locked=true;
state.resourceName=state.resourceName||s.resource;state.resourceMax=Number(state.resourceMax||100);state.resource=Number(state.resource??state.resourceMax);return state;};
P.track=function(state,id){P.init(state);return state.progression.tracks[id]||null;};
P.trackGain=function(state,id,amount=1,reason=""){const t=P.track(state,id);if(!t)return {changed:false,unlocks:[]};const old=t.mastery;t.mastery=Math.min(100,Math.max(0,t.mastery+amount));const nv=Math.max(t.value,1+Math.floor(t.mastery/18));const valueChanged=nv>t.value;t.value=nv;if(reason)t.history.push({day:state.day,reason,amount:Math.round((t.mastery-old)*10)/10});t.history=t.history.slice(-20);return {changed:t.mastery!==old,valueChanged,track:t,oldMastery:old,newMastery:t.mastery};};
P.addMetric=function(state,key,amount=1){P.init(state);const p=state.progression,s=SYSTEMS[state.world]||SYSTEMS["Custom World"];p.metrics[key]=(p.metrics[key]||0)+amount;if(p.literalLevels)return {ranked:false};const metric=p.metrics[s.rankMetric]||0;let idx=p.rankIndex;for(let i=0;i<s.rankRequirements.length;i++)if(metric>=s.rankRequirements[i])idx=Math.max(idx,i);idx=Math.min(idx,s.ranks.length-1);if(idx>p.rankIndex){p.rankIndex=idx;p.rank=s.ranks[idx];return {ranked:true,rank:p.rank};}return {ranked:false};};
P.addXp=function(state,amount){P.init(state);const p=state.progression;if(!p.literalLevels)return {levels:0};p.xp+=Math.max(0,Math.round(amount));let levels=0;while(p.xp>=p.xpNext){p.xp-=p.xpNext;p.level++;p.statPoints+=3;levels++;p.xpNext=Math.round(p.xpNext*1.18+35);}p.rank=String(p.level);return {levels};};
P.summary=function(state){P.init(state);const s=SYSTEMS[state.world]||SYSTEMS["Custom World"],p=state.progression;return {headline:s.headline,rankLabel:s.rankLabel,rank:p.literalLevels?`Level ${p.level}`:p.rank,resource:state.resourceName,tracks:Object.values(p.tracks),worldRules:s.worldRules,literalLevels:p.literalLevels,xp:p.xp,xpNext:p.xpNext};};
P.bestTrack=function(state){P.init(state);return Object.values(state.progression.tracks).sort((a,b)=>b.mastery-a.mastery)[0];};
window.WW_PROGRESSION=P;
})();
